![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [5]:
my_array = np.arange(10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
my_array[::-2]

array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [7]:
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
my_array[-2:-4:-1]

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [9]:
my_array[2::-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [2]:
matrix = np.arange(1,21).reshape(4,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
np.flip(matrix)

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [ ]:
matrix[:2,:2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [3]:
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
matrix[::2, ::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [ ]:
matrix[:3,::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [5]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [6]:
print(x[x == "Loro"])

['Loro' 'Loro']


In [8]:
np.where(x == "Loro")

(array([0, 3], dtype=int64),)

In [ ]:
x[np.where(x == "Loro")]

array(['Loro', 'Loro'], dtype='<U5')

In [9]:
x == "Loro"

array([ True, False, False,  True, False])

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [67]:
x = np.arange(20).reshape(2, 5, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [11]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
x.nbytes

80

In [13]:
x[3] = 1
print(x)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [87]:
y = np.arange(10, 50)
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [86]:
np.flip(y)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [15]:
j = np.array([1,2,0,0,4,0])
j

array([1, 2, 0, 0, 4, 0])

In [18]:
print(np.where(j != 0)[0])

[0 1 4]


In [19]:
def quitar_zeros(vector):
    return vector[vector != 0] 

In [20]:
quitar_zeros(j)

array([1, 2, 4])

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [ ]:
m = np.random.rand(10, 10)
m

array([[0.30955743, 0.52949194, 0.86861524, 0.66984808, 0.58494095,
        0.49712358, 0.15049184, 0.53010748, 0.82812489, 0.8017225 ],
       [0.16491109, 0.30772943, 0.97102096, 0.6057348 , 0.61020514,
        0.36728001, 0.95856201, 0.43987071, 0.18370311, 0.52941284],
       [0.12784421, 0.32170042, 0.73683724, 0.3790684 , 0.73972559,
        0.78642866, 0.84038122, 0.15148472, 0.10360576, 0.17729213],
       [0.83312733, 0.17091492, 0.13900177, 0.51413371, 0.0369826 ,
        0.03856601, 0.51849405, 0.68199633, 0.21817007, 0.54092277],
       [0.47090465, 0.98813736, 0.15668743, 0.40975725, 0.51503085,
        0.56876803, 0.68535013, 0.94126743, 0.18482514, 0.23299195],
       [0.8760431 , 0.18634807, 0.39508372, 0.11855087, 0.76687837,
        0.90877237, 0.44366245, 0.84783566, 0.61789249, 0.99981873],
       [0.11794769, 0.14571359, 0.60319015, 0.47997783, 0.2371759 ,
        0.99350973, 0.5453139 , 0.48906288, 0.9084107 , 0.17567831],
       [0.88874369, 0.48887355, 0.3431845

In [97]:
m.min()

0.03698259920321145

In [96]:
m.max()

0.9998187276341381

## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [ ]:
r = np.random.randint(0, 6, (100, 100))
r

array([[5, 1, 3, ..., 5, 1, 3],
       [2, 0, 1, ..., 2, 2, 5],
       [0, 0, 2, ..., 1, 3, 2],
       ...,
       [0, 0, 0, ..., 3, 3, 5],
       [0, 5, 5, ..., 0, 3, 5],
       [1, 3, 5, ..., 5, 1, 2]])

In [39]:
np.average(r)

: 

: 

In [100]:
r.size

30

## Ejercicio 15
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [8]:
w = np.random.randint(1, 11, (5, 5))
print(w)

[[ 4  7 10  7  2]
 [ 2  1  9  1  7]
 [ 2  1  8  1  7]
 [ 7  2  6  9  3]
 [ 3  3  2  8  4]]


In [13]:
matriz = (w - np.mean(w)) / np.std(w)

In [15]:
print(w)
print()
print(matriz)

[[ 4  7 10  7  2]
 [ 2  1  9  1  7]
 [ 2  1  8  1  7]
 [ 7  2  6  9  3]
 [ 3  3  2  8  4]]

[[-0.21785348  0.80333473  1.82452294  0.80333473 -0.89864563]
 [-0.89864563 -1.2390417   1.48412687 -1.2390417   0.80333473]
 [-0.89864563 -1.2390417   1.1437308  -1.2390417   0.80333473]
 [ 0.80333473 -0.89864563  0.46293866  1.48412687 -0.55824956]
 [-0.55824956 -0.55824956 -0.89864563  1.1437308  -0.21785348]]


In [ ]:
matriz.mean()

1.0769163338864018e-16

In [18]:
matriz.std()

0.9999999999999999

## Ejercicio 16
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [20]:
array1 = np.arange(11)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
array2 = np.where(((array1 >= 3) & (array1 <= 8)), -1, array1)
array2

array([ 0,  1,  2, -1, -1, -1, -1, -1, -1,  9, 10])

In [22]:
array3 = np.where(((array1 >= 3) & (array1 <= 8)), array1 * (-1), array1)

# array3 = np.concatenate((array1[:3], array1[9:]))
array3

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])